version: "3.8"

x-shared:
  zammad-service: &zammad-service
    environment: &zammad-environment
      MEMCACHE_SERVERS: zammad-memcached:11211
      POSTGRESQL_DB: zammad_production
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      POSTGRESQL_PORT: 5432
      POSTGRESQL_OPTIONS: ?pool=50
      REDIS_URL: redis://zammad-redis:6379
      BACKUP_DIR: /var/tmp/zammad
      BACKUP_TIME: 03:00
      HOLD_DAYS: 10
      TZ: Europe/Berlin
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASS: zammad
      ZAMMAD_USER: admin
      ZAMMAD_EMAIL: admin@domain.com
      ZAMMAD_PASSWORD: adminpassword
      STORAGE_BACKEND: FileSystem
      TICKET_BASE_URL: http://localhost:8080/api/v1/ # Keep internal URL consistent with Nginx internal port

    image: ghcr.io/zammad/zammad:6.5.0-75 # Using default version from .env combined
    restart: always
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis

services:
  zammad-backup:
    <<: *zammad-service
    command: ["zammad-backup"]
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-storage:/opt/zammad/storage:ro
    user: 0:0

  zammad-elasticsearch:
    image: bitnami/elasticsearch:8.18.0 # Using default version
    restart: always
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    environment:
      ELASTICSEARCH_ENABLE_SECURITY: 'true'
      ELASTICSEARCH_SKIP_TRANSPORT_TLS: 'true'
      ELASTICSEARCH_ENABLE_REST_TLS: 'false'
      ELASTICSEARCH_PASSWORD: zammad # Using default from .env combined

  zammad-init:
    <<: *zammad-service
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    restart: on-failure
    user: 0:0

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:1.6.38-alpine # Using default version
    restart: always

  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "8080" # Nginx internal listening port
    ports:
      - "80:8080" # Map external port 443 to internal port 8080
    depends_on:
      - zammad-railsserver

  zammad-postgresql:
    container_name: zammad-postgresql # From .env
    environment:
      POSTGRES_DB: zammad_production # From .env
      POSTGRES_USER: zammad # From .env
      POSTGRES_PASSWORD: zammad # From .env
    image: postgres:17.5-alpine # Using default version
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zammad-railsserver:
    container_name: zammad-railsserver # From .env
    <<: *zammad-service
    #command: ["zammad-railsserver"]
    entrypoint: ["/opt/zammad/custom-entrypoint.sh"]
    volumes:
      - ./custom-entrypoint.sh:/opt/zammad/custom-entrypoint.sh
    
  zammad-redis:
    container_name: zammad-redis # From .env
    image: redis:7.4.3-alpine # Using default version
    restart: always
    volumes:
      - redis-data:/data

  zammad-scheduler:
    <<: *zammad-service
    command: ["zammad-scheduler"]

  zammad-websocket:
    <<: *zammad-service
    command: ["zammad-websocket"]

volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  redis-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-storage:
    driver: local
